### ISSUE TITLE
Icons not loading in either Message Template Builder or Editor pages

### ISSUE THREAD

**Issue by gemmapotaka** [veda-consulting/uk.co.vedaconsulting.mosaico#12]
One error I am seeing with my Mosaico extension set up it is not displaying any images. On the civicrm/mosaico/index page I am not seeing the icons of the templates or of byVOXmail. I can get to the templates though when I go to edit them I also don't see the diagrams (see attached screenshots). I also cannot upload images into my templates, I get an "Unexpected upload error (SyntaxError: Unexpected end of input)"

I feel like this is to do with the location the images are being stored. On one of the image templates image links me to here /civicrm/mosaico/templates/versafix-1/edres/_full.png where I get a 404 Not Found error.

I checked the Extension Resource URL setting which is /sites/default/civicrm/extensions/.

I see that the files are missing are stored here but CiviCRM does not appear to be finding them  /sites/default/civicrm/extensions/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1/

![screen shot 2016-03-17 at 12 21 43 pm](https://cloud.githubusercontent.com/assets/6699521/13835278/2b33bc6a-ec5b-11e5-965f-be5eec455278.png)
![screen shot 2016-03-17 at 12 21 22 pm](https://cloud.githubusercontent.com/assets/6699521/13835279/2b3989a6-ec5b-11e5-99e8-e198d8a58a64.png)

**Comment by deepak-srivastava** [comment]
@gemmapotaka 
Check https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/6. Most likely php fileinfo extension is not loaded or enabled.

In our next release we would enforce some checks, to be able to catch such issues & inform.

**Comment by gemmapotaka** [comment]
Thanks

I have installed the latest release. It is not telling me anything with the installation is wrong but I am still missing the icons. The only change I noticed was the strip saying MOSAICO is no longer there and neither is the warning box.
I also checked that php fileinfo was enabled, which it was and is.

We are on CiviCRM 4.6.14 and drupal 7.43

**Comment by deepak-srivastava** [comment]
@gemmapotaka can i look at your install? Email me details on deepak at vedaconsulting.co.uk and i can take a quick look?

**Comment by petednz** [comment]
hi Deepak - Pete here from NZ - are you asking for a login to the site, or you want server access? Former is obviously easier - or perhaps we can skype briefly - should be up and awake 'late' here as we have an evening sports competition - so would be around eg 9.40 - 10 am your UK time. peterdavis59

**Comment by petednz** [comment]
You should have an admin user account email now.

**Comment by petednz** [comment]
just to clarify the path that civi is showing for the image when it doesn't load is

/civicrm/mosaico/templates/versafix-1/edres/_full.png

the image is located at (ie the image actually shows at) 

/sites/default/civicrm/extensions/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1/edres/_full.png 

so should something be replacing this bit with /civicrm

/sites/default/civicrm/extensions/uk.co.vedaconsulting.mosaico/packages

Our Resource path is

/sites/default/civicrm/extensions/

Our Directory path is 

/srv/www/fuzion/demo.fuzion.co.nz/sites/default/civicrm/extensions

**Comment by deepak-srivastava** [comment]
Thanks @petednz and @gemmapotaka for the access.

http://demo.fuzion.co.nz/civicrm/mosaico/templates/versafix-1/edres/_full.png in your setup is being looked as an absolute path to a file than php path, and therefore 404 error. Looks like an apache / htaccess config thing.

The php backend script renders the file by calculating the absolute path. In your case path would be http://demo.fuzion.co.nz/sites/default/civicrm/extensions/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1/edres/_full.png. Which doesn't work because php handler isn't being invoked.

Ideally the code should be using the urls like http://demo.fuzion.co.nz/civicrm/mosaico/templates?file=versafix-1/edres/_full.png to make sure it works for all cases. For now point is noted, and something for our next releases.
Meanwhile if you able to figure out the config fix, do share.

**Comment by deepak-srivastava** [comment]
@petednz, @gemmapotaka Also when i run http://demo.fuzion.co.nz/civicrm/mosaico/index?reset=1&runcheck=1 (with runcheck) i see this error message:
"ImageMagick not installed - Email Template Builder extension will not work."

It's possible that ImageMagick is not installed or Apache wasn't restarted after the install ?

Not sure if this leads to previous image loading issues, but might be worth checking.

**Comment by petednz** [comment]
Thanks. Checking those options

**Comment by dptarrant** [comment]
I have the same issue.  Thanks

**Comment by petednz** [comment]
Hi David. One thing. We are using NGINX not APACHE - might be part of the issue? You?

**Comment by dptarrant** [comment]
Apache - any guidance on what is the difference in this case?

Thanks

On Tue, Mar 22, 2016 at 2:19 PM, petednz <notifications@github.com> wrote:

> Hi David. One thing. We are using NGINX not APACHE - might be part of the
> issue? You?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/12#issuecomment-199949243>
>



-- 
David Tarrant
617-901-2513 (m)
dptarrant@gmail.com

**Comment by xurizaemon** [comment]
@deepak-srivastava hey - just a quick note to tell how we worked around this to get the extension up for testing.

I worked around the incorrect URLs with an NginX redirect, but I would suggest for best compatibility making sure the extension doesn't depend on manual webserver configuration or `.htaccess` modifications - .htaccess is an Apache extension, and many CiviCRM sites don't use Apache.

Here's the fix for NginX, but the best fix would be to ensure the URLs in the page refer to the static files via the extension directly rather than initialising CMS + CiviCRM for each request just to deliver each .png or .js file.

    rewrite ^/civicrm/mosaico/templates/(.*)$ /sites/default/civicrm/extensions/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/$1 permanent;

Imagemagick package was installed on the server, but the missing ingredient there was that the PHP imagemagick was not installed & enabled.

    sudo apt-get install php5-imagick

**Comment by deepak-srivastava** [comment]
@xurizaemon @petednz many thanks for looking into it and sharing the config solution. 
Do agree that extension should have the fix, than relying on web server configs. It is issues like these that we want to catch & fix before going to beta.

**Comment by veda-consulting** [comment]
Just wanted to add that the issues we're facing are partially down to the implementation of Mosaico and its expectancy of being stand alone to an extent. CiviCRM is the first substantial Open Source project to try and integrate in this way and it will help pave the way for others, however the result is its quite painful for the first few beta testers.

Thanks to everyone for getting involved and working round issues, it should mean a more robust CiviCRM integration and Mosaico becoming easier to integrate into other projects also.

**Comment by petednz** [comment]
@veda-consulting No worries - we are happy to help identify and where possible solve issues as we give this great tool a workout.

**Comment by deepak-srivastava** [comment]
UPDATE: released alpha4 which attempts to resolve icon/image loading issues without requiring a web-sever config fix. Can somebody give that a try. Thanks.

**Comment by deepak-srivastava** [comment]
Closing this ticket as enhancements been done with Apha4. Please re-open if you still see image/icon loading issues with alpha4. Thanks.
