### ISSUE TITLE
Requires unsubscribe/opt-out token to send email even though unsubscribe link is already in header

### ISSUE THREAD

**Issue by madurak** [veda-consulting/uk.co.vedaconsulting.mosaico#143]
Unsubscribe link is already in the header (of the email in template) but error message says it still requires unsubscribe/opt-out token to send the mail.
<img width="1391" alt="screen shot 2017-04-26 at 17 44 56" src="https://cloud.githubusercontent.com/assets/10810117/25446045/1b20040a-2aa8-11e7-9416-92b7b3bfe5f0.png">

**Comment by petednz** [comment]
I think the OP problem is that they haven't inserted {domain.address} token which is also required.

**Comment by petednz** [comment]
My observation is that trying to add eg OptOut via webpage token in to the footer block results in this <domain>/civicrm/mailing/optout?reset=1&jid=1763&qid=1763&h=fakehash showing in both the Preview and the Test.

**Comment by petednz** [comment]
I think the OP is simply failing because they haven't inserted {domain.address} token which is also required.

**Comment by totten** [comment]
I'm able to reproduce this problem.

This is sort of a Mosaico issue, but IMHO it really goes to the concept behind FlexMailer -- *extensions should be able to define new template syntaxes* . Mosaico is a basic example of this (because it adds  different syntax for the unsub tokens), but other use-cases (like Pug, Markdown, Mustache, or Smarty) could also have their own syntaxes for the unsub tokens. I'm going to work a bit toward making the CAN-SPAM validation tweakable through FlexMailer.

**Comment by totten** [comment]
Related: https://issues.civicrm.org/jira/browse/CRM-21472

**Comment by totten** [comment]
Depends: https://github.com/civicrm/org.civicrm.flexmailer/pull/9 and https://github.com/civicrm/civicrm-core/pull/11316

**Comment by totten** [comment]
For posterity: this should be fixed with the combination of  CiviCRM 4.7.29+, Mosaico 2.0-beta3+, and FlexMailer 0.2-alpha5+. If you run on an older version of CiviCRM 4.7.x:

 * The new code should degrade gracefully (e.g. no hard crashes, but same buggy behavior).
 * You can easily work-around by editing your content: simply change `[unsubscribe_link]` to `{action.unsubscribeUrl}`.
