### ISSUE TITLE
Allow access to edit Mosaico templates without access to send Mosaico mailings

### ISSUE THREAD

**Issue by mattwire** [veda-consulting/uk.co.vedaconsulting.mosaico#148]
(Original subject: " "Edit Message Templates" permission not respected for template editor ")
The "Mosaico Templates" menu item is not visible but if you know the URL (ie. a/#/mosaico-template) then you can use the template editor without the "Edit Message Templates permission.

**Comment by JKingsnorth** [comment]
Hi, I've just been testing this against the 2.0 beta.

If you go to that URL now without permissions, the editor does not load. Yay.

However, if you go to that URL now with the 'edit message templates' permission - it still doesn't load. This is because the angular module relies on the crmMailing angular module. The crmMailing module requires 'access civimail' permissions.

So to get around this issue, you can add 'edit message templates' to the list here: https://github.com/civicrm/civicrm-core/blob/245c62b82767b9c29697beec8ce88da0df660b1e/CRM/Mailing/Info.php#L67

However, that doesn't help with bringing the 'Mosaico Templates' option into the navigation menu. That would require changing permissions in  the XML. This is where we clash a bit with the 'Mailing workflow' functionality that is only supported by Drupal. So things get a bit messy.

**Comment by totten** [comment]
There seem to be a couple points.

There's the original point from @mattwire about user's hacking around to visit the screen (even if they don't have permission). For that, I agree/confirmed @JKingsnorth's comment you cannot *really* use the form. It just displays the list of templates (which is information you can get other ways -- eg when composing a mailing). So that's fine -- hacky users messing around with URLs get hacky (but safe) behavior.

Regarding the second point -- it seems to be saying that accessing this page effectively requires *both* `access CiviMail` *and* `edit message templates`. On a policy level, that seems fine by me (for a typical deployment).

Maybe there's some edge-case where an org wants to let someone edit Mosaico templates but *not* let them send mailings. IMHO, that's a niche requirement that's not on critical path -- but it's patch-welcome.

**Comment by mattwire** [comment]
@totten From memory, I *think* what was happening was:
* Without the "Edit message templates" permission you should not be able to edit the message templates, but you could.  The menu entry would be hidden but you could still access the page.

I found this when trying to lock down a demo site and wanted to restrict access to a user so they could create mailings but not create/edit templates.
