### ISSUE TITLE
Hyperlinks need preceeding http / https

### ISSUE THREAD

**Issue by freedomlives** [veda-consulting/uk.co.vedaconsulting.mosaico#168]
e.g. if I enter in the website as: www.example.com it is treated as a directory.  While everyone _should_ enter https://www.example.com, having the form check for a missing http or https and fill in at least http would be good.

**Comment by totten** [comment]
Agree that's confusing. Also, in my testing, it seems like this is true of many hyperlinks (not just social blocks).

As a mitigating consideration... if you enter a URL that isn't a well-formed, absolute URL, the Mosaico UI will highlight it with red... but the link is still accepted. 

The behavior of accepting invalid-ish URLs in the GUi is (at the moment) useful. Why? Because (as mentioned in #154) links can also be generated from tokens like `{action.forward}` -- which would not (from a normal perspective) be considered a well-formed link.

Ideally, the validation would be a little louder (harder to ignore for genuinely bad links) and a little more nuanced (accepting URLs with either a URL scheme `/^(https?|ftp|mailto|...):/` or a `{token}`.).
