### ISSUE TITLE
Ampersand in url is converted to entity

### ISSUE THREAD

**Issue by scardinius** [veda-consulting/uk.co.vedaconsulting.mosaico#175]
Hi,

I realized that links with additional params are converted to use entity of ampersand. Example:

* link http://www.example.org/?first=1&second=2
* after saving, value in civicrm_mailing.body_html: http://www.example.org/?first=1&amp%3Bsecond=2

& => \&amp; => &amp%3B

Therefore It's not possible to properly parse such query string:

    parse_str('first=1&amp%3Bsecond=2', $arr);
    print_r($arr);
    // Array
    // (
    //    [first] => 1
    //    [amp;second] => 2
    //)

Do you have a idea what to do in such situation?

**Comment by scardinius** [comment]
Hi,

one small mistake, I'm talking about only **& => \&amp;** conversion but the result is the same - it's not possible to properly parse query string.

    parse_str('first=1&amp;second=2', $arr);
    print_r($arr);
    // Array
    // (
    //    [first] => 1
    //    [amp;second] => 2
    //)

**Comment by totten** [comment]
It looked odd to me when I first saw `&amp;` in an `href`, but I think this is actually correct behavior:

 * When I do the [Manual Test: Images and Links](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.x/TESTING.md#manual-tests-images-and-links) and use some links with ampersands, the links *behave* correctly (in all listed scenarios).
 * According to https://stackoverflow.com/questions/3705591/do-i-encode-ampersands-in-a-href , it is actually expected that one encodes HTML entities within `href="..."` (etal). The subtly is that most humans (when writing HTML) don't do that, so the browsers are fairly forgiving. (And apparently that forgiveness may even become a standard?!)
 * In practice, most funny characters in URLs are converted to `%12` notation before they get into HTML, and `%` doesn't require any special HTML entities, so we... almost never hear about weird character issues in an HREF. However, the `&` is probably the one oddball character.

I don't know the context of parsing you need to do. If one were using an HTML or XML parser, I'd expect it to decode entities automatically. (Hopefully, it uses the same weird tricks as a web-browser to recognize both bare `&` and `&amp;`.) OTOH, if one were doing some regex, then you'd need to imitate the XML parser a little bit, e.g.

```php
$string = 'first=1&amp;second=2';
parse_str(html_entity_decode($string), $arr);
print_r($arr);
// Array
// (
//     [first] => 1
//     [second] => 2
// )
```

Closing because the behavior seems correct. If you find otherwise, feel free to reopen.
