### ISSUE TITLE
Saving Template for use in Scheduled Reminders

### ISSUE THREAD

**Issue by dsuguy2007** [veda-consulting/uk.co.vedaconsulting.mosaico#185]
Am I missing something? 
I created a template in Mosaico, saved it. but It doesn't show up as an option in Scheduled Reminders. 

How do I get a Mosaico template to show up within Scheduled Reminders?

Running D7, civi 4.7.21, mosaico 2.0-beta2.1494950412

**Comment by natewilldo** [comment]
Join the Make it Happen campaign to add this feature! https://civicrm.org/make-it-happen

**Comment by totten** [comment]
__Background__: 
* In `v1.x`, Mosaico templates were primarily stored as "Message Templates" (which you could use in CiviMail, Scheduled Reminders, etal).
* The primary change in `v2.x` was to bypass "Message Templates" and integrate directly into CiviMail.

__Opinion__: Integration between "Mosaico" and "Message Templates" is a mixed blessing -- it's flexible, but it's also complicated -- there's more screens to click through, and exporting complex HTML to CKEditor can lead to new mistakes. But if you like power-tools and can do your own support, then it's a cost-effective technique to make the templates more versatile.

__New Extension__: I took a few hours and made "Message Template" support for v2.x. This is packaged as a separate extension:

https://github.com/civicrm/org.civicrm.mosaicomsgtpl

I've done some light testing, and it seems to work. The extension is flagged "experimental/unsupported" because it's an unfunded power-tool that I don't really want to support. However, if somebody wants to take ownership of it, then ping me.
