### ISSUE TITLE
Images appear as malformed text

### ISSUE THREAD

**Issue by andersiversen** [veda-consulting/uk.co.vedaconsulting.mosaico#186]
I'm seeing this (attached image), when trying to use the extension and adding a block with images.
I'm on civicrm 4.7.17 and just installed mosaico today.
I also installed imagemagick (and restarted apache)
![civicrm](https://user-images.githubusercontent.com/1169244/29970045-538b2f1a-8f23-11e7-8955-0dcf4c22351a.png)
There's no errors in the console, no 404s, and cannot find anything in the php or apache error/access logs.
One thing: I installed mosaico, then found out I didn,t have imagemagick, then uninstalled mosaico (but didn't remove), installed imagemagick, and reinstalled mosaico.
Any and all help apreciated.

**Comment by bhahumanists** [comment]
Are you on WordPress? I've seen this issue when it's a WordPress install and WP is in its own folder rather than at the root of the domain.

**Comment by andersiversen** [comment]
No I'm on Drupal 7

**Comment by mattwire** [comment]
What version of the mosaico extension are you using?

**Comment by andersiversen** [comment]
I'm using 2.0-beta2

**Comment by mattwire** [comment]
You could try my version and see if it works there: https://github.com/mattwire/uk.co.vedaconsulting.mosaico/releases/tag/2.0-beta3-mjwconsult3

**Comment by andersiversen** [comment]
Hey Matt, I've tried it - same problem.

**Comment by kngs** [comment]
I'm seeing this problem on a WP site (4.7.24) which used to work fine with Mosaico images.  (view in browser is now broken too). No upgrades have been done though there was a server kernal upgrade (noticed a similar issue over a year ago which may have been linked to PHP/Apache).  Other WP Mosaico installs are still working fine.  I'm assuming I can try mattwire beta 3 version of code without any DB schema changes!?!?

**Comment by mattwire** [comment]
@kngs There are no db schema changes but I would make a backup first, as the actual mosaico template version increases from 0.15 to 0.16 (I think the changes are very minimal but have not investigated whether there would be any impact going back).  You'd have to edit and save the template for it to actually cause any problem though.  Be good to hear your feedback with my version.

**Comment by kngs** [comment]
Sorry it took a bit for me to try this out.  Unfortunately, it did not resolve the problem.  I was initially able to upload an image but then it disappeared in the view once I clicked away (as before) :/

**Comment by tim1mw** [comment]
We've been having a similar problem, both with the drag-n-drop and when using the upload button, using both Chrome and Firefox. Using WordPress 4.8.3, CiviCRM 4.7.23, Mosaico plugin 1.0.

With drag-n-drop, the image will fail to appear, if the upload button is used then the image will appear briefly on the page and then disappear again. With FF it will then be replaced with a "broken image" icon, Chrome simply shows an empty space. If you look in the network logging console on FF, then it shows an initially successful get request for the upload image from the wordpress uploads area (this URL can be manually copied to a browser tab and successfully opened), this is immediately followed by second GET request which gives a 404 error, this request is in the following form:

https://myserver.com/civicrm?page=CiviCRM&q=civicrm/mosaico/img&src=https%3A%2F%2Fmy-server.com%2Fwp-content%2Fuploads%2Fcivicrm%2Fpersist%2Fcontribute%2Fuploaded_image_b6acc986d00f68e2b7afb723ef7d9e34.jpg&method=resize&params=258%2Cnull

There are no errors in the underlying server log (with php debugging on).

**Comment by totten** [comment]
I've tried to reproduce this:
 * General environment: Ubuntu with Apache 2.4, PHP 5.6, and MySQL 5.7.
 * Site/Build: [wpmaster](https://github.com/civicrm/civicrm-buildkit/tree/master/app/config/wp-demo) -- WordPress 4.7.3, CiviCRM 4.7.29 prerelease (`master` branch), latest code for Shoreditch/FlexMailer/Mosaico 2.x code from git
 * Browser: Firefox 54 or Chrome 62 

So I make a new mailing and drop in an image from the desktop.  This works. I inspect the source for the uploaded image, and the URL looks like this
`http://wpmaster.l/?page=CiviCRM&q=civicrm/mosaico/img&src=http%3A%2F%2Fwpmaster.l%2Fwp-content%2Fuploads%2Fcivicrm%2Fpersist%2Fcontribute%2Fimages%2Fuploads%2FcrmUiSelectExample_a7b383bfaa2934bebbf9698a106ae24a.png&method=resize&params=258%2Cnull`. 

There's a slight difference with your URL (`http://myserver.com/?page=CiviCRM` vs `http://myserver.com/civicrm?page=CiviCRM`). Someone like @kcristiano might understand the difference better, but (on my system) it seems academic -- because I'm able to view the image either way.

A few things y'all might check:
 * [Enable debugging and back-traces. Locate the CiviCRM log file](https://docs.civicrm.org/dev/en/latest/tools/debugging/)
 * Create a new mailing.
 * Open the Firefox/Chrome developer tool and monitor the network requests.
 * Drop in the image.
 * In the browser dev tool, look for a POST call. See if it succeeded, failed, or didn't appear at all. Try to find the response.
 * Check the CiviCRM log file.

For reference, on my system, there's a successful POST to `http://wpmaster.l/wp-admin/admin.php?page=CiviCRM&q=civicrm/mosaico/upload` which looks like:

![screenshot from 2017-11-24 21-22-42](https://user-images.githubusercontent.com/1336047/33227692-a92f5c94-d15d-11e7-918e-cc51cf8b3246.png)

**Comment by andersiversen** [comment]
Hi again
I've tried to do as Totten suggests, and it seems to all just work, the post is successfull, the image is there on the server. I can upload and see images in the gallery. But still the error remains: there's no placeholder image, just the text "drop an image here" and i cannot drop an image on it (a little blue bordered square approx. 20x20px appears when hovering the image). Using the button, I have the same result as tim1mw.
For reference I'm on Drupal 7, Civi 4.7.17, Mosaico 2.0-beta3 (from github).

Here is the code of the placeholder image tag in the template:
  `<img border="0" hspace="0" vspace="0" width="166" class="mobile-full" alt="" data-bind="virtualAttrStyle: 'vertical-align: top; '+'width: 100%; '+'height: auto; '+'max-width: '+(imageWidth()+'px')+';'+'', virtualAttr: { width: imageWidth(), alt: image().alt() }, wysiwygSrc: { width: imageWidth(), height: null, src: image().src, placeholder: { width: imageWidth(), height: 130, text: 'w'+imageWidth()+''} }" style="vertical-align: top; width: 100%; height: auto; max-width: 166px;" src="https://example.com/civicrm/mosaico/img?method=placeholder&amp;params=166%2C130">` 

Here is the code after using the image upload button (the text "drop an image here" disappears after uploading): 
  `<img border="0" hspace="0" vspace="0" width="166" class="mobile-full" alt="" data-bind="virtualAttrStyle: 'vertical-align: top; '+'width: 100%; '+'height: auto; '+'max-width: '+(imageWidth()+'px')+';'+'', virtualAttr: { width: imageWidth(), alt: image().alt() }, wysiwygSrc: { width: imageWidth(), height: null, src: image().src, placeholder: { width: imageWidth(), height: 130, text: 'w'+imageWidth()+''} }" style="vertical-align: top; width: 100%; height: auto; max-width: 166px; display: block;" src="https://example.com/civicrm/mosaico/img?src=https%3A%2F%2Fexample.com%2Fsites%2Fdefault%2Ffiles%2Fcivicrm%2Fpersist%2Fcontribute%2Fimages%2Fuploads%2Fbackground_a64b410e27e53562ef956aef7e6b930e.jpg&amp;method=resize&amp;params=166%2Cnull">`

**Comment by totten** [comment]
What happens if you take those image URLs and open them directly?

 * `https://example.com/civicrm/mosaico/img?method=placeholder&params=166%2C130`
 * `https://example.com/civicrm/mosaico/img?src=https%3A%2F%2Fexample.com%2Fsites%2Fdefault%2Ffiles%2Fcivicrm%2Fpersist%2Fcontribute%2Fimages%2Fuploads%2Fbackground_a64b410e27e53562ef956aef7e6b930e.jpg&method=resize&params=166%2Cnull`
 * (_Edit_: The HTML snippet displays ampersands as `&amp;`; for directly opening the link, you'd just want `&`.)


If the server raised an error while handling `civicrm/mosaico/img`, then it would certainly muck up the layout. 

Ex: If I hack at my local system and force it to generate errors for `civicrm/mosaico/img`, and if I use Chrome as the browser, then it produces a bad layout much like your screenshot.

<img width="742" alt="screen shot 2017-12-05 at 1 52 43 pm" src="https://user-images.githubusercontent.com/1336047/33632944-0c588688-d9c4-11e7-9eb2-d327b7c9f044.png">

In that case, the question would be -- what error arises when requesting that image URL?

**Comment by totten** [comment]
Since I'm not able to reproduce the problem organically, let me share a little more context/speculation -- the basic symptom here is that the image request for `civicrm/mosaico/img` appears to be broken. That could mean either:

 * (a) The client is requesting the wrong URL. (Perhaps an incorrect-base, cross-domain issue, or encoding issue.)
 * (b) The client is requesting the right URL, but the server encounters a problem. (Perhaps some kind of environmental/compatibility/permission issue with PHP-ImageMagick or with the data-storage for images?)

Based on @andersiversen's report, that case doesn't sound like (a) -- so there's at least one system experiencing (b). I don't have that problem myself, but if you have a system with this problem, then you might investigate/trace/debug the underlying functions [processImg()](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/d84f2c9/CRM/Mosaico/Utils.php#L241 ), [resizeImage()](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/d84f2c9/CRM/Mosaico/Utils.php#L340), and [_mosaico_civicrm_check_dirs()](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/d84f2c9e97a7d357e4790e93bf262f2271538555/mosaico.php#L279).

**Comment by andersiversen** [comment]
It's definitely a case of B. If I go to the image URL's directly the images are shown, but the generated image is 0x0px, so something goes wrong there.
I still don't see any errors in the logs.

**Comment by andersiversen** [comment]
The console in Firefox perhaps gave a hint (I use chrome normally):
applyBindings: 400.57ms       mosaico.min.js:2582:289
Source map error: request failed with status 401
Resource URL: https://example.com/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.mosaico/packages/mosaico/dist/mosaico.min.js?v=0.15?&=llis4
Source Map URL: mosaico.min.js.map

**Comment by francescbassas** [comment]
I get this error on local, not in real environment. If I try to access to a disappeared image like civicrm/mosaico/img?method=placeholder&params=208%2C130

I get this error:
```
ImagickException: "non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3190"

#0 /var/www/html/sites/all/civicrm_ext/uk.co.vedaconsulting.mosaico/CRM/Mosaico/Utils.php(299): Imagick->drawimage(Object(ImagickDraw))
#1 [internal function](): CRM_Mosaico_Utils::processImg()
#2 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(276): call_user_func((Array:2))
#3 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:14))
#4 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#5 /var/www/html/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:3))
#6 [internal function](): civicrm_invoke("mosaico", "img")
#7 /var/www/html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#8 /var/www/html/index.php(21): menu_execute_active_handler()
#9 {main}
```

**Comment by totten** [comment]
@andersiversen - FWIW, the source map generally shouldn't be necessary for correct execution. It's a helper file to allow browser-based debugging. However, it is odd that it reports an HTTP 401  ("Unauthorized"). Suggests something like an httpd configuration issue or security tool/plugin run amok?

@francescbassas That is an interesting error. There are some reports on the imagick issue tracker which sound similar -- e.g. https://github.com/ImageMagick/ImageMagick/issues/371 or https://github.com/ImageMagick/ImageMagick/issues/374. You might be able to find more via Google.

To all - It might be useful for everyone experiencing this problem to report:

 * General build/OS/stack (e.g. stock Ubuntu 16.04; e.g. cPanel EasyApache; e.g. MAMP 3.5; Ubuntu with special PPAs)
 * PHP Version
 * ImageMagick version

FWIW, the last two systems I've tested (which successfully display the placeholders):
 * MAMP 3.5, PHP 5.6.10, ImageMagick 6.8.9
 * Ubuntu 16.04 (Desktop Edition), PHP 7.0.22, ImageMagick 6.8.9

I've used commands like these to inspect what versions are being loaded for PHP:

```
$ php --version
PHP 5.6.10 (cli) (built: Jul  6 2015 14:28:54)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with XCache v3.2.1, Copyright (c) 2005-2014, by mOo
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans
    with XCache Optimizer v3.2.1, Copyright (c) 2005-2014, by mOo
    with XCache Cacher v3.2.1, Copyright (c) 2005-2014, by mOo
    with XCache Coverager v3.2.1, Copyright (c) 2005-2014, by mOo

$ php -r '$i=new Imagick();print_r($i->getVersion());'
Array
(
    [versionNumber] => 1673
    [versionString] => ImageMagick 6.8.9-7 Q16 x86_64 2015-07-06 http://www.imagemagick.org
```

**Comment by francescbassas** [comment]
My local runs a docker container builded with this Dockerfile:

```
FROM php:5.6-apache

RUN a2enmod rewrite

# install modules of apache that will be required for Drupal 7
RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev && \
	rm -rf /var/lib/apt/lists/* && docker-php-ext-configure gd \
	--with-png-dir=/usr --with-jpeg-dir=/usr && docker-php-ext-install gd
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install mbstring
RUN docker-php-ext-install zip

## ImageMagick - Mosaico 2.0.beta2 requirement

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libmagickwand-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pecl install imagick-3.4.1 \
    && docker-php-ext-enable imagick
```
**PHP 5.6.9, ImageMagick 6.8.9-9**

@totten I debug a little and I can see that comenting this [line](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.0-beta3/CRM/Mosaico/Utils.php#L297)

`$draw->annotation(0, 0, $width . " x " . $height);`

images are rendered well (without size text).

**Comment by totten** [comment]
@francescbassas Hmm, I've only used the stock Ubuntu build of imagemagick/php. The discussion in https://github.com/ImageMagick/ImageMagick/issues/374 suggests there may be other dependencies -- esp. relating to freetype, fonts, and ghostscript.

**Comment by nganivet** [comment]
@andersiversen Had the same issue and resolved it by installing ImageMagick. Make sure it is properly installed (the library, and the PHP extension) and working, this might resolve your issue.

**Comment by totten** [comment]
Thanks for sharing, @nganivet. It does make sense that images would fail to render if ImageMagick was missing.

What's odd to me... there is a check in https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.x/mosaico.php#L191. If it doesn't find imagick, then it's supposed to raise a critical error and prevent the user from opening Mosaico. The fact that users are having the problem *despite* the test suggests the test isn't quite accurate -- e.g. maybe it signals that "php-imagemagick" is missing, but it doesn't signal that "imagemagick does not have any fonts".

What we might do is have a more aggressive test -- e.g. *actually render an image with text*. If that fails, raise a critical error that blocks Mosaico usage.

**Comment by highfalutin** [comment]
I was having the same symptoms and found a fix. I'm not sure if the underlying problem was the same as in the OP, but FWIW, this is the solution I found.

on:
MAMP running PHP 5.6.27
ImageMagick 6.9.6-2 Q16 x86_64 2016-10-24
WordPress 4.9.5
Civi 5.0.1
Mosaico 2.0-beta3.1512698300
CiviCRM Bootstrap theme 0.1-alpha15
FlexMailer 0.2-alpha5

I was seeing 404 errors in the browser console when trying to load placeholder images like this:
`http://localhost/civicrm?page=CiviCRM&q=civicrm/mosaico/img&method=placeholder&params=640%2C200`

Loading the URL manually in the browser gave the error "The requested URL /civicrm was not found on this server".

Turns out [I didn't have WordPress permalinks configured properly](https://civicrm.stackexchange.com/questions/658/pointing-to-civicrm-breaks-wordpress-site-404-http-response). Very simple fix.

**Comment by herbdool** [comment]
I'm seeing exactly the same issue, though it's on a Drupal 7 multilingual site. The images get uploaded but don't appear in the editor. The images are there in the final email and can be accessed directly by pasting the queried url referenced in the html. When I paste in the full url, e.g. `http://website.ca/en/civicrm/mosaico/img?src=...` then it shows an empty img. I've tested this extension on a fresh local install and don't have the same issue, so there's something with this site which, once it's been debugged, will paste results here. Both local and the first sites are using Mosaico 2.0-beta4...

**Comment by francescbassas** [comment]
@totten current Mosaico 2.0-beta4 doesn't have the refactor image backend. Can a beta5 version be released to facilitate testing your solution?

**Comment by guyiac** [comment]
For what it's worth, I had this problem, and found out that although I was loading imagemagick on the global php.ini (which allowed me to get by the CiviCRM dependency check), there was a local php.ini (that a previous dev had put there) that didn't have imagemagkick. When I deleted that local php.ini, everything started working correctly.

**Comment by adixon** [comment]
Late to this game, but confirming some of the previous posts, i.e. I had a similar user experience as the initial issue post and I also saw errors in the civicrm error log as reported by others (e.g. #issuecomment-350992431).

My setup was debian stretch on docker, and what might be useful is to note that in building the image, I did not include the imagemagick package, since it said that it was just a placeholder for dependencies (https://packages.debian.org/stretch/imagemagick). I did include the library and the php extension, and this extension did work in other respects (and I could upload images with some funky workarounds).

When I found this thread, I added the imagemagick package to my docker image and that resolved the issue. So, presumably one of those dependencies was the problem - I noted that installing the package did install a bunch of fonts.

For the minimalist, there's probably a subset of those dependencies that could be installed, but as far as this issue goes, I'd recommend we just close it (if indeed installing the imagemagick package resolves the original poster's issue).

Other experiences of the same symptom may have different solutions.

Specifically - I'd guess that for @herbdool the issue is how paths get rewritten with multilingual Drupal - sometimes you'll need to add in some extra .htaccess rules to avoid bad resource urls.

**Comment by francescbassas** [comment]
@adixon Would you know to tell me what is missing in [this docker configuration](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/186#issuecomment-351200085)?

**Comment by adixon** [comment]
Yes, include the imagemagick package, e.g. on line 6 just before the last ampersand.

**Comment by francescbassas** [comment]
It's this!! Adding imagemagick package the images are loaded correctly. Thanks @adixon.

```
FROM php:5.6-apache

RUN a2enmod rewrite

# install modules of apache that will be required for Drupal 7
RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev imagemagick && \
	rm -rf /var/lib/apt/lists/* && docker-php-ext-configure gd \
	--with-png-dir=/usr --with-jpeg-dir=/usr && docker-php-ext-install gd
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install mbstring
RUN docker-php-ext-install zip
RUN docker-php-ext-install bcmath

## ImageMagick - Mosaico 2.0.beta4 requirement

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libmagickwand-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pecl install imagick-3.4.1 \
    && docker-php-ext-enable imagick
```

**Comment by adixon** [comment]
Great, and I hope no one else is going to use that, and that you're going to update to php 7.1+ real soon. There's a mattermost channel dedicated to docker, you might find that a good place for followup.

**Comment by andersiversen** [comment]
The patch in [this comment](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/292#issuecomment-497709542) in issue #292 solves my issue here - after 2 years! Finally we can start using Mosaico :)
I'll close the issue - hope everyone out there has found a solution. It seems to me that many different scenarios could cause this problem.

**Comment by bmango** [comment]
I know this issue is closed but I am experiencing the same problem after upgrading from Mosaico 2.1 to 2.2. When I try and add a block with an image, the placeholder image is not shown which breaks the layout and I am unable to click on the upload image icon - it disappears as I move towards it with the mouse in Chrome. Luckily in Firefox, even though the placeholder image does not show, I am able to reach the upload image button. I checked the console log in Chrome and the following error is showing:

`GET https://wfto.com/civicrm/mosaico/img?method=placeholder&params=258%2C150 403 (Forbidden) - img:1`

The output from the headers are:
```
Request URL: https://xxx.com/civicrm/mosaico/img?method=placeholder&params=258%2C150
Request Method: GET
Status Code: 403 Forbidden
Remote Address: xxx.10.57.10:443
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Headers: origin, x-requested-with, content-type
Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Cache-Control: no-cache, must-revalidate
Connection: close
Content-Encoding: gzip
Content-Language: en
Content-Length: 17845
Content-Type: image/png
Date: Thu, 24 Oct 2019 13:17:00 GMT
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Link: <https://xxx.com/>; rel="canonical",<https://xxx.com/>; rel="shortlink"
Server: Apache
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Generator: Drupal 7 (https://www.drupal.org)
Accept: image/webp,image/apng,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Cookie: ...
DNT: 1
Host: xxx.com
Referer: https://xxx.com/civicrm/mosaico/iframe?snippet=1
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
method: placeholder
params: 258,150
```

We did have a lot of problems installing ImageMagick in the first place. 

The platform I'm on is ubuntu 16.04 php 7.3.9 

I tried to find out what version of Imagemagick I'm running. Looking at the phpinfo() it tells me 3.4.4

When I run:

```
$ php -r '$i=new Imagick();print_r($i->getVersion());'

PHP Fatal error:  Uncaught Error: Class 'Imagick' not found in Command line code:1
Stack trace:
#0 {main}
  thrown in Command line code on line 1

```
When I run the same code from the website (using Drupal php Eval) I get:

`Array
(
    [versionNumber] => 1673
    [versionString] => ImageMagick 6.8.9-9 Q16 x86_64 2019-06-15 http://www.imagemagick.org
)`

So it seems a bit of a mess! 

I am using Drupal 7.67 with CiviCRM 5.18.3

**Comment by caracolmzd** [comment]
@bmango join us on the dark-side:
#340

**Comment by bmango** [comment]
I found the solution to the issue for me by following the steps given by aydun at [Looking for missing placeholder and social media images? #340](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/340#issuecomment-545849527). Thanks to ginkgomzd for referencing! :)

**Comment by pullingshots** [comment]
I ran into this issue with a fresh install of Mosaico 2.3.1572289217 and CiviCRM 5.24.4 on Drupal 7.69 (running on ubuntu 18.04 and stock php 7.2 including php-imagick).
The solution for me was the one referenced by deepak-srivastava at https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/292#issuecomment-497709542
