### ISSUE TITLE
Error when saving edits to a template or sending email

### ISSUE THREAD

**Issue by themak1985** [veda-consulting/uk.co.vedaconsulting.mosaico#193]
I get the following error: Sorry an error occurred and your information was not saved.

Wordpress 4.8.2 and CiviCRM 4.7.24 - using beta 2.0 - daily - also happened on V2 beta release.

No backtrace generated.

**Comment by themak1985** [comment]
Discovered issue - Wordfence, a popular wordpress plugin that acts as a firewall was blocking the requests from Mosaico/CiviCRM.  If you are also experiencing this issue - you do not have to disable Wordfence.  Go to Live Traffic in Wordfence  and you should find a blocked request like this:

> location left DOMAIN/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fa%2F and was blocked by firewall for XSS: Cross Site Scripting in POST body: json=%%%domain_id%%%reply_id%%%unsubscribe_id%… at DOMAIN/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fajax%2Frest

Simply select "Whitelist Param From Firewall" and the issue will be resolved.

**Comment by totten** [comment]
Thanks for sharing.

Aside: It sounds like that tool uses some kind of heuristic to detect possible XSS. This sounds familiar -- CiviCRM bundles in a similar tool (PHPIDS), so we periodically have to refine that whitelist. I'll close the issue here since the topic of "aligning XSS heuristics" is really a bigger scope than this one extension. But if someone has time/incentive to work on that general problem, it'd be cool.
