### ISSUE TITLE
Preheader results in poor open rate

### ISSUE THREAD

**Issue by MegaphoneJon** [veda-consulting/uk.co.vedaconsulting.mosaico#218]
Many email clients (Gmail, Outlook, Apple Mail, etc.) will show a "preview line" by default, which is derived from the plain-text version of the email.

The default pre-header causes the preview line to be "Unsubscribe View in your browser".  While it's not difficult for a savvy Civimail user to disable the pre-header, the default is going to result in an unattractive preview, which will hurt open rates in Civimail compared to competing tools.

I'm not sure what the best approach is, since the pre-header is a special case.  My thoughts are that either a) it should become a "post-footer", or b) it's excluded from the HTML to plaintext conversion.

![selection_329](https://user-images.githubusercontent.com/1796012/33248050-9d59c460-d2f0-11e7-8ec5-086e65c7738c.png)

**Comment by totten** [comment]
This is a good point, and I'm also not certain either.

IMHO, from a design/policy perspective, (a) feels better than (b). These links are important -- they should be available in the textual rendition.

I'm a little hesitant about (a) because it would require deviating more from upstream's code. I wonder if upstream has put any thought into this? (CC @bago)

Aside: It'd be really cool if the email clients accepted a bit of metadata to precisely control the preview blurb. Have you tried searching generally for discussion about manipulating the email preview?

**Comment by bago** [comment]
The preheader block in versafix-1 let you insert a text to be used as preheader. Just select the preheader block and look at the "Content" tab for the "PreHeader Text" input field. Simply write your sentence there and you will make your gmail happy.

PS: are you sure the preheader comes from the text version of the email and not from the first text found in the html version?

**Comment by francescbassas** [comment]
It would be interesting that it could be marked as a required field before being sent. Or at least to show some warning if the field is empty.

**Comment by bago** [comment]
If you have a proposal with a good UX for mosaico-model warnings about things in the whole template that could be "non-validating" or simply "not-optimal" without creating a big usability PITA, I'm happy to evaluate it.

Buttons without links, lorem-ipsum text left there, placeholder images not being replaced, grammar issues in the text, bad text/image ratio, awful images, bad color contrasts, too few or too much text, too small or too big texts: every single issue could deserve a warning and the preheader is not more important than this one.

**Comment by francescbassas** [comment]
Sure! Being able to check all of this would be great. I imagine a pseudoelement before 'Close' and 'Test' buttons on navbar indicating if there are errors/warnings or not. Then if click there it would take a list of the detailed information of the warnings and errors detected in the left sidebar.

**Comment by totten** [comment]
Ah, that Pre-Header input is a cool feature! I like that a bit more than the idea of moving the header links. But I agree that it raises a general validation/UX issue.

My first impulse for a UX was the same as @francescbassas  -- e.g. add an icon to the toolbar. That's a common idiom for tasks/todos -- for example, this screenshot from Gitlab:

<img width="417" alt="screen shot 2017-12-05 at 10 01 57 am" src="https://user-images.githubusercontent.com/1336047/33624069-ffaa7296-d9a7-11e7-941e-e8cd030f7e83.png">

But on second thought, it's easy to build up a backlog -- if the user adds three blocks, and each block comes with 2-4 tips, then it can quickly build up a scary number. And the number would be detached from context, so it'd be awkward to correct. If I got started and quickly saw 12 todos, I might run and hide under the bed.

One could put the tips in the gutter, adjacent to the blocks which have issues. Maybe mouse-over for details. Here's a really rough mockup:

<img width="1093" alt="screen shot 2017-12-05 at 10 33 21 am" src="https://user-images.githubusercontent.com/1336047/33624145-3ecf1b34-d9a8-11e7-9cd5-3c6d80011775.png">

(Maybe the left-hand gutter would make more sense? Put the tips geographically closer to the main toolbox? To make it less scary, perhaps choose diminutive colors that fade into the background?)

**Comment by francescbassas** [comment]
Like your block contextual indicators proposal. For details I think it would be better to place them in the sidebar instead of a mouse-over tooltip.

**Comment by bago** [comment]
I appreciate you start understanding some of the UX issues.

Please note that mosaico is "template based" so the mosaico library doesn't really know what the blocks will be and what shape they will have and how many contents (and using which widgets) they have. But let's pretend this can be solved adding some new template language directive and let's talk about the UX.

Please note that a 3 columns block with image+title+text+button by default will have to show "default image not replaced"x3 + "defautl title not edited"x3, "default text not edited"x3, "default button text non edited"x3 "missing link for button"x3, so by default you will have 15 warnings for this very block as soon as you drop it.

How do other email template editors deal with this issue? As far as I know they don't deal with this at all... maybe for the same reason Word doesn't complain if you try to save an empty document or a document with broken images or broken links.

At this time I still think this kind of feature is really complex to be developed and will result in a confusing UI/UX that will create more issues than the solved ones. That said, I'm open to discussion and proposals (or, even better, code PR)

**Comment by totten** [comment]
The Word analogy is good for things like the *default title of a block* or the *default label of a button* or the *placeholder image*. Like in a Word document, all these elements are visually manifest when you skim the canvas. The user's main job is to skim and update that canvas.

The analogy breaks down for things like *pre-header text* or *button URLs* or *social media URLs*. If you skim the document as a new user, then *you're initially unaware the options exist* because *the options are invisible by default*. Figuring these out requires some mix of training, exploration, or learning "the hard way" (sending broken emails).

One could limit the alerts to invisible issues. For a 3 column block, there are only x3 invisible inputs that must be considered -- the x3 buttons which default to blank URLs. (Going from x15 to x3 helps UX, but it doesn't really reduce the dev work -- we'd still need to implement UI+validation, and that's probably not trivial...)

---

Going back to @MegaphoneJon's original point and re-interpreting... Basically, I think he's saying: *Don't send a scary preheader by default*.

In the interest of KISS, we could just copy the `Subject` to the `preheaderText`? (Specifically, set a default value for the pre-header as token `[subject]` -- then the server can evaluate the token at the same time as `[unsubscribe_link]`.) I'm not too sharp with Knockout, but maybe https://gist.github.com/totten/4e3d0e4b577274494d6d82ccf44f9bb4 ? It's not as fine-tuned as entering the pre-header manually, but it should be less scary by default.

(Come to think of it, maybe do the same thing for the unconfigurable `<title>`?)

**Comment by bago** [comment]
IF the mosaico editing happens AFTER you set the title and you know your master template structure then you can simply start a viewModel plugin with some code like this:
```
var plugin = function(vm) {
      if (typeof vm.content().titleText == 'function') vm.content().titleText("my title");
      if (typeof vm.content().preheaderBlock == 'function') vm.content().preheaderBlock().preheaderText("my title");
}
```
Otherwise if you want to replace it after editing then:
```
var plugin = function(vm) {
      if (typeof vm.content().titleText == 'function') vm.content().titleText("[title]");
      if (typeof vm.content().preheaderBlock == 'function') vm.content().preheaderBlock().preheaderText("[preheader]");
}
```
and then have some postprocessor to replace it.

BTW: I don't think repeating the subject will make your email so much better than showing unsubscribe/view in browser. If you are aware of preview text and you care about it you should really write there something useful, not the subject.

Back to the validation stuff... is the empty ALT text an hidden validation issue?

If your user doesn't understand Mosaico have a "Content Tab" then he will miss most of the feature and will be unable to use Mosaico... whenever we add a new UI element we'll make the UI more complex and it will be easier for the user to miss some other important UI element, so I need to be sure this validation issue is a real issue and our users are not arguing about that (this is the first report about this preheader stuff from the userbase). We did a lot of real user testing on Mosaico UI and all of them sooner or later found how to insert the link for a button, so they found the "Content Tab". Our main UX issue, at this time, is some people don't look at the content in that tab and they don't understand they can remove buttons, so they delete button titles and leave the button there... Some other user never find the Style tab and think they can only send grey emails.

**Comment by wflanagan** [comment]
I think, related to this, we have the preheader rendering in versafix-1 in Outlook when it is explicitly turned off in content. The consequence of this is that emails forwarded look horrible in outlook. 

Seems like some better control of preheader is a good plan.
