### ISSUE TITLE
Text block is too basic - ordered/unordered lists + add image

### ISSUE THREAD

**Issue by KairosCanada** [veda-consulting/uk.co.vedaconsulting.mosaico#238]
Why isn't there an option to add a bulleted list in a text block?
Why can't we add a photo and wrap text around it?
Why can't we upload photos via URL?

These are some basic things that you will need to develop if you want users to stick with Mosaico.

Staff not familiar with HTML expect templates to work like a Word document. If you ask them to look at the source code they get flustered and won't use it, even for something as simple as bullets.

**Comment by MegaphoneJon** [comment]
@KairosCanada - I'm not one of the devs of this extension, but the short answer is "because no one has written these features".  

A slightly longer answer:
* Mosaico is a project that's separate from CiviCRM.  This repository merely packages Mosaico for use within CiviCRM.  Feature requests for Mosaico itself should go to the [Mosaico team](https://github.com/voidlabs/mosaico).
* While this software is free to use, it isn't free to write.  It's not effective to demand something of people who have already given you so much of their work with no benefit to themselves.  Offering resources to help them meet your goals is a better approach.  If your organization is unwilling/unable to prioritize those goals, your best hope is that someone else with your goals feels differently.

**Comment by themak1985** [comment]
@KairosCanada - @MegaphoneJon  is right - if the dev-team isn't supported to implement the features, they won't be implemented. by support I mean $$$ or development time (coding).

- Bulleted lists is a feature that has been implemented in the latest Mosaico - not sure when exactly it was implemented, but its in v0.17.3 - however - it will need to be implemented into this CiviCRM version. 
- As far as the other features, such as wrapping text around an image - its my understanding you can do this via html or through integration with TinyMCE - though you would again need to provide $$$ or development time to implement this.

**Comment by tbuytaer** [comment]
I would be interested in having the bulleted list button too.

I found this issue from upstream mosaico that says it can be done by adding a "mosaico plugin" but I don't know how this should be set. If someone can give me a pointer I can try to see if I can do this.
https://github.com/voidlabs/mosaico/issues/194

**Comment by homotechsual** [comment]
We've issued a PR to change the defaults for the editor in CiviCRM's implementation of Mosaico. It involves no changes to Mosaico instead overriding these at the point the CiviCRM calls Mosaico.
