### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by mattwire** [veda-consulting/uk.co.vedaconsulting.mosaico#255]
We really need to draw a line and make a formal 2.0 release before considering new features / updates to mosaico.

# To merge/fix before 2.0 Final:
- #186 Images appear as malformed text (Unidentified Imagemagick incompatibility)
- #268 Mailing has not been saved, Content maybe out of date, please refresh the page and try again

# Release notes (Work in Progress)

- #235 Fix small HTML validation errors
- #234 MixinCtrl - Fix weird title on preview dialog
- #232 Ensure that mosaico upgrader sets the schema version in civicrm_extension not civicrm_setting so its domain independent
- #167/#248 Fix memory leak sending mail to larger groups (over 400 contacts)
- #210 Mosaico.setting.php - Switch default layout back to single-page
- #236 Introduces an alternative layout based on the crm-* CSS convention.
- #249/#257 Alter loading of unsubscribe groups and preview groups to be dynamic to reduce DOM Load and add performance improvements.

**Comment by mattwire** [comment]
@totten @deepak-srivastava We've got too much inconsistency in mosaico versions at the moment and the last tagged release is 2.0-beta3.  Let's get these two PRs merged and release a 2.0.

**Comment by lsh-0** [comment]
especially since there is this on the release page:

> Note: v1.x is no longer officially supported. Please download / upgrade to v2.x.

with no 2.0 release.

**Comment by totten** [comment]
Thank you, @mattwire. Looks like #249 has been merged, so I'll move it down to "Release notes (Work in Progress)".

Agree that's several fixes merged -- and we should get these out. I'm inclined to call it `2.0-beta4` rather than `2.0` -- mainly because we haven't had any progress (fix or warning or doc or explanation or work-around) for #186.

**Comment by andrewperry** [comment]
Does v1.1 even work on Civi 5.x? Doesn't seem to on the fresh install we've done recently.  The extensions directory should not show it, if it doesn't work.

**Comment by jamienovick** [comment]
Re: https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/210

@totten a change of this magnitude should have the appropriate review. I'm also concerned that were reverting weeks of work that has been paid for by a client to design, style and test a solution that is being used in the wild by several thousand sites. Also note that this will break Shoreditch tests so has knock on effects. I'd add that the designs were also subjectively tested with the opposite results with the paying clients - people who are actually using this solution. I've got no idea why this change is being made given that we don't have any feedback requesting it (and lots of feedback that the old Civimail screen was not user friendly!).

Ive left comments on that ticket but a few points:

1. Putting a screen in front of people and asking then to chose is not a great way of gathering meaningful feedback. We should be asking users to perform a task and seeing how quickly they can achieve it and/or where they get stuck. This is an objective measurement. People are very bad at knowing what is 'best'.

2. I'd question whether the people in the room were the right people to ask. The people in the room at a CiviCRM related event are largely engaged or existing users and/or consultants and implementors. We should be testing this with an audience of new users of the CRM, or those who have never used it before and specifically those who are coming from other mailing applications such as MailChimp.

Our feedback from training sessions with users is that they want wizards/simplified screens with clear logical steps that make them confident that they are doing things in the correct order. Too many options on a screen makes people lose confidence. We haven't had any negative feedback on the wizard layout at all... ever!

Users coming from MailChimp and other applications are used to the wizard approach.

If we want to do some proper testing of this in order to validate whether a change is required can I suggest a different approach?

We should make it easy in the CiviMail component settings to select between the screens. We should then gather pingback statistics on which people do pick and base our decision on a larger sample size of actual users. In an ideal world we would probably have a layout selected at random on install and see what the amount that 'switch' are. After a period (say 6 months) we evaluate the data and pick a final solution.

Short of that I would suggest that we stick with what we have and notify users that they can select an option when they first instal letting them make an informed choice.

I have serious concerns about unilaterally changing the UX for such a major component at this stage and as such I would argue that we need to get appropriate data to support such a change.

**Comment by totten** [comment]
You make good points about other ways to get insight (e.g. watch people as they try a task; e.g. collecting stats).

I think some of the energy here may be based on misinformation -- e.g. *the default hasn't actually changed in the way the ticket suggests* (i.e. the same Shoreditch config still produces the same default layout); e.g. there is already a setting to choose between screens; e.g. the results reported in #210 were from a mixed audience at an NGO tech event -- the event was not CiviCRM focused.

**Comment by jamienovick** [comment]
(i.e. the same Shoreditch config still produces the same default layout); 

Doesn't it depend on the order you install things in? If our install script installs mosaico before Shoreditch does that mean we will have an issue or does the setting automatically change when Shoreditch is installed?

I am concerned though, we are splitting the install base. This is a really significant change Tim and not one to be taken as lightly as it clearly has been. For good or for bad we have 1750+ installs in the wild with the existing flow and changing the installer means that we will have to consider both as part of any future UX improvements. 

If we are going to make this change, from something that has been out there for over 9 months we need a lot more data to support it.

**Comment by lsh-0** [comment]
> Does v1.1 even work on Civi 5.x? Doesn't seem to on the fresh install we've done recently.

there is an upcoming [security release for Civi 5.x](https://civicrm.org/blog/dev-team/civicrm-53-release) and no mention of a patch for Civi 4.7.x. Does Mosaico support release 1.1 on Civi 5.x? or must we upgrade to the still-beta v2?

**Comment by totten** [comment]
(Aside for the record: the conversation about layouts continued separately in #210.)

**Comment by alexandre-lim** [comment]
Hello, is it safe to install Mosaico 2.0-beta4 on Civi 5.x+ ? Or should we wait for stable release ? Thank you

**Comment by homotechsual** [comment]
This looks semi-stalled which is a shame - this came up at the sprint as Mosaico (being great) was suggested to a number of newer users who duly went to their CiviCRMs and installed Mosaico - to receive via the UI version 1.1 which doesn't work on 5.6.0 and they also get a nice message telling them that there's a newer version available - which appeared to them quite scary because it ends "beta4".

**Comment by Upperholme** [comment]
I'd love to get this installed on some of the sites I look after where bulk email is used a lot. I'm unclear however as to whether Mosaico is actually ready for prime time. There seems to be a lot of issues. Is the current beta4 useable in the real world?

**Comment by homotechsual** [comment]
Yes - this is useable in the real world in the beta4 state - we're using this live on 10+ client sites.

**Comment by Upperholme** [comment]
Thanks. That's really helpful.

**Comment by alexandre-lim** [comment]
@MikeyMJCO Thanks for your feedback !

**Comment by Rar9** [comment]
What the current best way /version to get the  Mosaico extension to fully work with last civicrm version?
