### ISSUE TITLE
Upgrading from beta 3 to beta 4

### ISSUE THREAD

**Issue by guyiac** [veda-consulting/uk.co.vedaconsulting.mosaico#297]
is there a way to upgrade from beta 3 to beta 4 without losing the Mosaico templates that are already built?

**Comment by mattwire** [comment]
I don't think you do lose the templates that are already built?

**Comment by guyiac** [comment]
The only way I know to upgrade is to uninstall beta 3 and install beta 4, because you don't get an option to do a regular extension upgrade in app. When I've done that before, i lost the templates that were built,

**Comment by mattwire** [comment]
Makes sense, because it's not published for release as it's not marked stable.  But you should just be able to replace the beta3 files with the beta4 files, clear caches and run the extension upgrader "in-app".  I'm pretty sure that normally works.  Another reason we should be marking mosaico as released... https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/255

**Comment by guyiac** [comment]
You were right! it worked.

Thanks for the tip. :-)
