### ISSUE TITLE
Easy to misclick away and lose saved progress on WordPress

### ISSUE THREAD

**Issue by simonjohnparker** [veda-consulting/uk.co.vedaconsulting.mosaico#319]
Hello,

On Wordpress, running into a frustrating issue quite a lot.

When modifying a template, it's so easy to accidentally click the top bar:
<img width="1680" alt="Screenshot 2019-07-16 at 13 49 38" src="https://user-images.githubusercontent.com/43149642/61295840-d6c85480-a7d0-11e9-929f-8a31d7460ae2.png">

This results in navigating away from Mosaico and losing any unsaved progress, as it doesn't appear autosave exists.

On the usual WP pages/posts even though it autosaves, you still get this warning when you accidentally click to navigate away:
<img width="1680" alt="Screenshot 2019-07-16 at 13 42 39" src="https://user-images.githubusercontent.com/43149642/61295971-142ce200-a7d1-11e9-9d31-326f488130b5.png">

Is it possible to implement something similar with Mosaico?

Although you can disable the top black bar, I don't' want to do that as it's useful the rest of the time.

**Comment by Upperholme** [comment]
I've had the same issue with Drupal - putting a newsletter together, move the mouse to the 'Blocks' menu item, overshoot slightly which causes the 'Search menu to drop down, and instead of clicking on 'Blocks' I've clicked on 'Find Contacts' and a lot of work is immediately lost. A pop-up alert as suggested would save the day. I've certainly lost several hours work through this, combined with the lack of autosave.

**Comment by johncronan** [comment]
It happened to me within 20 minutes of starting to use the extension!

**Comment by mwestergaard** [comment]
Been there, done that!

**Comment by Barijohn** [comment]
We've also had client request something like this to stop them navigating away from the page. 

Or could a Save button be added instead of having to Close the page down to save the work done.

**Comment by colemanw** [comment]
Looks like this issue can be closed @mattwire
