### ISSUE TITLE
Empty imageBlock tables appear when re-using templates

### ISSUE THREAD

**Issue by scoobird** [veda-consulting/uk.co.vedaconsulting.mosaico#348]
One of our clients recently reported seeing big boxes containing a broken image after sending a mailing created using an existing template. It is not apparent how to remove these, as they don't appear when configuring the mailing, but appear only in certain email clients or when forwarding the message. The appearance of the email in browser (in Thunderbird the box is much taller) and an example of one of the empty divs is below. 

Any ideas of where this is coming from, or how to ensure mailings do not contain them?

![image](https://user-images.githubusercontent.com/7529633/69464763-446f2900-0d4d-11ea-87ad-c0e1b8d6c12b.png)

```


<table class="vb-outer" width="100%" cellpadding="0" border="0" cellspacing="0" bgcolor="#000000" style="background-color: #000000;" id="ko_imageBlock_4">
    <tbody><tr>
      <td class="vb-outer" valign="top" align="center" style="padding-left: 9px; padding-right: 9px;">

<!--[if (gte mso 9)|(lte ie 8)]><table align="center" border="0" cellspacing="0" cellpadding="0" width="570"><tr><td align="center" valign="top"><![endif]-->
<div class="oldwebkit" style="max-width: 570px;">
        <table width="570" class="vb-container fullwidth" cellpadding="0" border="0" bgcolor="#ffffff" align="center" cellspacing="0" style="border-collapse: separate; padding-left: 0; padding-right: 0; width: 100%; max-width: 570px; background-color: #ffffff;">
          <tbody><tr>
            <td valign="top" align="center">
              <img hspace="0" border="0" vspace="0" width="570" class="mobile-full" alt="" style="border: 0px; max-width: 570px; display: block; border-radius: 0px; width: 100%; height: auto; font-size: 13px; font-family: Arial, Helvetica, sans-serif; color: #3f3f3f;" src="https://www.url.org/civicrm/mosaico/img?src=https%3A%2F%2Fwww.url.org%2Fsites%2Fdefault%2Ffiles%2Fcivicrm%2Fpersist%2Fcontribute%2FImageThatDoesntExist.png&amp;method=resize&amp;params=570%2Cnull">
            </td>
          </tr>
        </tbody></table>
        </div>
<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->
      </td>
    </tr>
  </tbody></table>
```

**Comment by caracolmzd** [comment]
@scoobird , this superficially looks like it could be the same issue as #340 .
I would guess that the user is using Chrome to compose and preview the mailing. In Chrome, 404 images do not get a placeholder, so it's easy to miss that there is anything wrong with the template.

**Comment by ebehiri** [comment]
Have the same issue. The ImageBlock appears in different sizes (See screenshots) in different browsers or devices. 
But I know how it happened, just don't know why. In my template, I was trying to drag and drop a picture over an existing one with the intent of replacing it. The drag and drop did not work, so I deleted the existing pic, but instead of reverting to the empty block (With the grey area for the size of the picture) it just showed a small thinner placeholder, into which I could not drag and drop a picture. Then that placeholder "disappeared" from the GUI. It's still there because I can move existing blocks above it or below it (They really don't move, that's how I know its there) but it is not shown and just cannot be deleted. 
I was using Chrome. Changing the browser after the fact did not help. 
This is in Outlook:
![image](https://user-images.githubusercontent.com/46088718/71311277-21877180-23ec-11ea-8d85-e074bf88f2d1.png)
This is in iPhone:
![image](https://user-images.githubusercontent.com/46088718/71311434-f05b7100-23ec-11ea-8cd6-94dc563becd9.png)

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
