### ISSUE TITLE
Emoji support in Emails

### ISSUE THREAD

**Issue by RastaTux** [veda-consulting/uk.co.vedaconsulting.mosaico#402]
Hello,

One of my collegues asked me if it is possible to add Emojis, especially to an email subject. Or also in the email content. Did someone test this? Is there something that needs to be added to the Mosaico Extension itself? We are using **2.0-beta4**, but there is nothing about this mentioned in never releases. The first step in my eyes may be to change our database to **utf8mb4**. What do you think?

Greetings,

Jonas

**Comment by MegaphoneJon** [comment]
There are some basic emojis that don't require utf8mb4.  I expect that Mosaico will work as-is if the database is converted, though it would need testing.

Note that conversation to utf8mb4 needs to be done at the PHP level and not just the MySQL level.  Work has been done to support this, but isn't considered release-quality at this time. See https://github.com/civicrm/civicrm-core/pull/15969.

Also see https://lab.civicrm.org/dev/core/-/issues/339 for discussion; it seems this fails when millions of records exist.  You'll also need to be running the latest CiviCRM (5.29) because it fixes bugs related to creating temp tables with utf8 (which causes unindexed queries when joined to a utf8mb4 table).

**Comment by RastaTux** [comment]
Okay.. thank you for your feedback! You can close this issue or use it as a feature request in your ticket system. Thx!
