### ISSUE TITLE
DB Error: no such table & Custom Templates URL 

### ISSUE THREAD

**Issue by MikeKleven** [veda-consulting/uk.co.vedaconsulting.mosaico#407]
Hi, 
I am new to Mosaico today.  I’m trying to integrate it with CiviCRM.  I have added the extension.  I am having trouble opening Mosaico Templates from within CiviCRM.  I receive the error message “DB Error: no such table.”  

I have looked though the documentation and searched here and I cannot find instructions about what to enter for the Mosaico Custom Templates URL in the Mosaico Settings on the CiviCRM Administer page.  Any direction would be helpful.  

Mike
![Capture](https://user-images.githubusercontent.com/64862965/99104306-7b65cc80-25a6-11eb-943e-c2cd4df01225.JPG)

**Comment by MegaphoneJon** [comment]
@MikeKleven Those settings all look fine, and should be unrelated to the error you received.  Unfortunately, there's not enough detail on that error to give you better help.  Could you please check out how to get [more detailed error messages](https://docs.civicrm.org/sysadmin/en/latest/troubleshooting/#debugging) in the documentation?

Also, you may have better luck posting to https://civicrm.stackexchange.com first, which is aimed at user support.  If there turns out to be a bug in the software rather than something specific to your install, this would be the appropriate place.

**Comment by MikeKleven** [comment]
Jon,

Thanks for replying so quickly.  I found someone else with the same issue.  Turning off the Content Tokens extension solved the problem.

Mike
