### ISSUE TITLE
Update to latest version of versafix-template.

### ISSUE THREAD

**Issue by seantwalsh** [veda-consulting/uk.co.vedaconsulting.mosaico#430]
Using mosaico for several clients and notice that the version of the versafix-template is 1.0.5 not the latest 1.1.19. What is needed to get this updated? Happy to contribute!

**Comment by eileenmcnaughton** [comment]
@MikeyMJCO I feel like you know the answer here

**Comment by homotechsual** [comment]
An update to the Mosaico library fork and probably the extension. The newest Versafix template uses features not available in the library we're using/bundling.

**Comment by seantwalsh** [comment]
@eileenmcnaughton @MikeyMJCO thanks for the quick replies.

Is the Mosaico library fork public?

**Comment by homotechsual** [comment]
https://github.com/civicrm/mosaico

**Comment by homotechsual** [comment]
Branch 0.15-civicrm-2

**Comment by seantwalsh** [comment]
Looks like some work is going on in #237 that might fix this as well.

**Comment by francescbassas** [comment]
Currently versafix-template-1 is based on (6-7 years old) 1.0.5 version. https://github.com/civicrm/mosaico/releases/tag/v0.15-civicrm-2.1

There are many updates since then, some requested in this repository. The latest version of the template is 1.3.2.

I think we have two options to update the template:

- Merge all changes from 1.05 to 1.32 (I think too risky)
- Create new template "versafix-template" (for example) and keep "versafix-template-1" for compatibility and try to keep this template updated from now on. For new installs, I would hide the old version by default.

**Comment by eileenmcnaughton** [comment]
I think @francescbassas approach sounds sensible - @mattwire ?

**Comment by mattwire** [comment]
This was updated in 3.0 release
