### ISSUE TITLE
Update to Versafix footer social icons - replace Google+ with TikTok

### ISSUE THREAD

**Issue by gomba777** [veda-consulting/uk.co.vedaconsulting.mosaico#542]
Hello and thanks a million time for all your work!

Would it be possible to replace the outdated Google+ icon in the versafix footer with the TikTok one?

Thanks!

**Comment by francescbassas** [comment]
This is implemented since 1.3.1 Versafix Template https://github.com/voidlabs/versafix-template/releases/tag/v1.3.1

You can try to download the latest version of this non CiviCRM repo and see if it works for you, or push on this other issue https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/issues/430

**Comment by mattwire** [comment]
Versafix updated in 3.0
