### ISSUE TITLE
{literal} {/literal} on top of each email

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.mosaico#66]
I designed an email using the versatile template, designing process works like a charm.
But when I send the email before the mail is rendered the following text is seen.
{literal} {/literal} 
What can I do about it? Is it a bug?

**Comment by deepak-srivastava** [comment]
Do you have CIVICRM_MAIL_SMARTY turned on? What happens if you switch it off.

Code tries to inject literal tags when smarty is turned on - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/CRM/Mosaico/Utils.php#L339
Or remove if turned off. Its possible that its unable to remove, may be because template is modified or something or head tag no longer exist for some reason?

Is it happening with all the templates or any new ones you create or just the existing ones?

**Comment by mattwire** [comment]
Please update to 2.0  1.x is no longer supported
